name: Chocolatine

on:
    push:
        branches-ignore:
            - " ga-ignore-"
    pull_request:
        branches-ignore:
            - " ga-ignore-"

jobs:
    mirroring_repo:
        runs-on: ubuntu-latest
        if: github.event_name == 'push'
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: mirror to epitech repo
              uses: pixta-dev/repository-mirroring-action@v1
              with:
                target_repo_url: ${{ vars.MIRROR_URL }}
                ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
